---
fullnameOverride: order-postgres
global:
  postgresql:
    postgresqlUsername: postgres
    postgresqlPassword: postgres
initdbUser: postgres
initdbPassword: postgres
initdbScripts:
  dbinit.sql: |
    CREATE DATABASE "borrowings" OWNER postgres;
    \connect borrowing
    ALTER DATABASE "borrowings" SET TIMEZONE TO 'Europe/Rome';
    SET TIMEZONE TO 'Europe/Rome';

    CREATE TABLE "borrowings"
    (
        borrowing_id integer,
        customer_id character varying,
        notify character varying,
        customer integer,
        start_borrow character varying,
        end_borrow character varying,
        book integer
    ) TABLESPACE pg_default;

    ALTER TABLE "borrowings"
        OWNER to postgres;
